// Generated by CoffeeScript 1.6.3
var displayPage, leading, old_pieceName, pass, pieceName, prev, sofar, tailing, upper;

old_pieceName = function(nom, nom1, chap, chap1, ver1, nom2, chap2, ver2) {
  var ans, them1, them2;
  them1 = ver1.split(' ');
  them2 = ver2.split(' ');
  ver1 = them1[0];
  ver2 = them2[them2.length - 1];
  if ((nom !== '' && nom !== nom1) || (chap !== chap1)) {
    if (!(ver1 === '1' && chap1 === '1')) {
      nom1 = nom;
      if (ver1 !== '1') {
        chap1 = chap;
      }
    }
  }
  ans = "" + nom1 + " " + chap1 + (nom1 === nom2 ? (chap1 === chap2 ? '' : '-' + chap2) : '-' + nom2 + ' ' + chap2);
  return ans;
};

pieceName = function(nom, nom1, chap, chap1, ver1, nom2, chap2, ver2) {
  var ans, them1, them2;
  them1 = ver1.split(' ');
  them2 = ver2.split(' ');
  ver1 = them1[0];
  ver2 = them2[them2.length - 1];
  if ((nom !== '' && nom !== nom1) || (chap !== chap1)) {
    if (!(ver1 === '1' && chap1 === '1')) {
      nom1 = nom;
      if (ver1 !== '1') {
        chap1 = chap;
      }
    }
  }
  ans = "" + nom1 + " " + chap1 + ":" + ver1 + (nom1 === nom2 ? (chap1 === chap2 ? (ver1 === ver2 ? '' : '-' + ver2) : '-' + chap2 + ':' + ver2) : '-' + nom2 + ' ' + chap2 + ':' + ver2);
  return ans;
};

leading = function(n1, c1, ln) {
  if (n1 === '' || c1 === '') {
    return ln;
  } else {
    if ((ln !== n1) && ln !== '') {
      return '';
    } else {
      return "" + n1 + " " + c1;
    }
  }
};

tailing = function(n1, c1, ln) {
  if (n1 === '' || c1 === '') {
    return ln;
  } else {
    if ((ln !== n1) && ln !== '') {
      return '';
    } else {
      return "" + n1 + " " + c1;
    }
  }
};

sofar = 0;

upper = 0;

pass = 1;

prev = 0;

displayPage = function(cpt) {
  var dig, pc;
  dig = parseInt(cpt);
  if (dig < sofar) {
    pass = 2;
    console.log('Second pass ...');
    upper = parseFloat(sofar.toFixed(2));
  }
  sofar = dig;
  if (pass > 1) {
    pc = (parseFloat(dig.toFixed(2)) / upper) * 100.00;
    if (prev !== dig) {
      console.log("" + (pc.toFixed(1)) + "%");
    }
  } else {
    if (sofar === 1) {
      console.log('First pass ...');
    }
  }
  return prev = dig;
};

Prince.addScriptFunc('leading', leading);

Prince.addScriptFunc('tailing', tailing);

Prince.addScriptFunc('displayPage', displayPage);
